### ISSUE TITLE
Other Languages - Indonesian

### ISSUE THREAD

**Issue by danirisdiandita** [as-ideas/TransformerTTS#111]
Is it compatible with other languages? I want to train this model using Indonesian language dataset. If possible, I want to know which variables that I need to change & consider. Thanks

**Comment by JDamour** [comment]
> Is it compatible with other languages? I want to train this model using Indonesian language dataset. If possible, I want to know which variables that I need to change & consider. Thanks

Me too, I would like to know about another language.

**Comment by solie** [comment]
@danirisdiandita it seems uses espeak language list as lang tokenizer. I'm currently training for javanese dataset, but I use 'id' as tokenizer, since no javanese support in espeak. Still in train_aligner step (and already 7 hours, 51%). I guess you can just modify the config and change 'en-us' to 'id' and try to train.

**Comment by PatrykNeubauer** [comment]
>Is it compatible with other languages? 

It is indeed, I've trained the model with success for polish. 
As @solie said you need to change the language of espeak to your own, you can check whether yours is supported [here](http://espeak.sourceforge.net/languages.html). Also make sure that you set the right sample rate. 
Both the language and sample rate are set in .yaml config files.
You should also change _alphabet in data/text/symbols.py to alphabet of your language, if it contains characters that aren't in english. 
These changes should be enough to get  the model working for another language, but keep in mind that you should also train the vocoder since GANs don't really handle change of speakers well from what I know.

**Comment by ManavJain2210** [comment]
You can also transliterate your dataset to english using [polyglot ](https://polyglot.readthedocs.io/en/latest/Transliteration.html) and train your model. And, change 'en-us' to 'en' in training_config.yaml. 
This method gave me a good result for hindi.

**Comment by danirisdiandita** [comment]
Hi, it works quite well in the Indonesian language by setting the language to `id` + training my own melgan vocoder. Without a vocoder, the result seems robotic but still shows the language well enough. After adding my own vocoder, the result is quite okay, but sometimes, minor glitches occur.
