### ISSUE TITLE
Sample rate and mono/stereo in configuration

### ISSUE THREAD

**Issue by padmalcom** [as-ideas/TransformerTTS#25]
Hi, I use training data at a sample rate of 16000 hz in mono (see https://www.caito.de/2019/01/the-m-ailabs-speech-dataset/ for more information).

Do I have to set the `sampling_rate` in `data_config.yaml` to 16000 before I start the training or what does this rate refer to? And is there a difference between using stereo or mono files?

Thanks for you help.

**Comment by pizzabug** [comment]
Hi! `create-dataset.py` uses librosa to import the wavs and automatically resamples the wav files to `sampling_rate` in preprocessing. 

I've left it at 22050 because the MelGAN vocoder is fixed to 22050 hz, but `sampling_rate` doesn't have to be changed to reflect the dataset. I hope that helps.

**Comment by cfrancesco** [comment]
@pizzabug is exactly right, if you want the model to be usable with the pretrained vocoders leave it at 22050, otherwise you can change it to 16000 or anything that you find works well.

I am not sure regarding the stereo-mono question, in principle as long as it is possible to extract power spectrograms there should be no issue within the TTS model.
