### ISSUE TITLE
Best way to reduce GPU memory usage

### ISSUE THREAD

**Issue by padmalcom** [as-ideas/TransformerTTS#31]
Using arount 70k wav files (18GB) I get an OOM from tensorflow on iteration ~80k. What is the best way to reduce the memory usage of my GPU (TITAN RX with ~22GB RAM)? Would it be the batch size in `autoregressive_config.yaml` or would you recommend to reduce the training data?

**Comment by cfrancesco** [comment]
Reduce batch size, this is most likely happening due to the costly attention. Total dataset size shouldn't matter too much as Tensorflow's Dataset is supposed to handle this. You can also remove the dynamic memory allocation at the beginning of the script if you don't mind using all the memory all the time.

**Comment by padmalcom** [comment]
Thank you for the quick reply, I'll try a lower batch size then.
